const icons = {
	XLogo: '/images/icons/socials/icon-x.svg',
	XLogoBlue: '/images/icons/socials/icon-x-blue.svg',
	XLogoWhite: '/images/icons/socials/icon-x-white.svg',
	TelegramLogo: '/images/icons/socials/icon-telegram.svg',
	GithubLogo: '/images/icons/socials/icon-github.svg',
	GithubLogoBlue: '/images/icons/socials/icon-github-blue.svg',
	DiscordLogo: '/images/icons/socials/icon-discord.svg',
	FacebookLogo: '/images/icons/socials/icon-facebook-white.svg',
	FacebookLogoDark: '/images/icons/socials/icon-facebook.svg',

	confirmedIcon: '/images/icons/icon-yes.svg',
	confirmedIconWhite: '/images/icons/icon-yes-white.svg',
	topRightArrowIcon: '/images/icons/icon-top-right-arrow.svg',
	searchIcon: '/images/icons/icon-search.svg',
	arrowDownIcon: '/images/icons/icon-arrow-down.svg',
	arrowDownIconGreen: '/images/icons/icon-arrow-down-green.svg',
	arrowDownIconGray: '/images/icons/icon-arrow-down-gray.svg',
	arrowLeftIcon: '/images/icons/icon-arrow-left.svg',
	arrowRightIcon: '/images/icons/icon-arrow-right.svg',
	arrowTopRight16Icon: '/images/icons/icon-arrow-top-right-blue-16.svg',
	globeIcon: '/images/icons/icon-globe.svg',
	closeIcon: '/images/icons/icon-close.svg',
	closeIconGray: '/images/icons/icon-close-gray.svg',
	menuIcon: '/images/icons/icon-menu.svg',
	cartIconGreen: '/images/icons/icon-cart-green.svg',
	cartIconWhite: '/images/icons/icon-cart-white.svg',
	checkedIcon: '/images/icons/icon-checked.svg',
	markerIcon: '/images/icons/icon-marker.svg',
	markerIconZero: '/images/icons/icon-marker-zero.svg',
	trashIcon: '/images/icons/icon-trash.svg',
	alertIcon: '/images/icons/icon-alert.svg',
	partyIcon: '/images/icons/icon-party.svg',
	errorIcon: '/images/icons/icon-error.svg',
	deleteIcon: '/images/icons/icon-delete.svg',
	
	ethIconBlue: '/images/icons/icon-eth-blue.svg',
	ethIconBlue12: '/images/icons/icon-eth-blue-12.svg',
};

export default icons;
